### ISSUE TITLE
Installing on Laravel 5.1

### ISSUE THREAD

**Issue by imyque** [unicodeveloper/jusibe-php-lib#4]
Hi, 

I got this error while installing this package to my laravel 5.1 project:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install unicodeveloper/jusibe-php-lib 1.0.1
    - Conclusion: remove vlucas/phpdotenv 1.1.x-dev
    - Installation request for unicodeveloper/jusibe-php-lib ^1.0 -> satisfiable by unicodeveloper/jusibe-php-lib[1.0.0, 1.0.1].
    - Conclusion: don't install vlucas/phpdotenv 1.1.x-dev
    - unicodeveloper/jusibe-php-lib 1.0.0 requires vlucas/phpdotenv ^2.2 -> satisfiable by vlucas/phpdotenv[2.2.x-dev, 2.3.x-dev, 2.4.x-dev, v2.2.0, v2.2.1, v2.3.0, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[2.2.x-dev, 1.1.x-dev].
    - Can only install one of: vlucas/phpdotenv[2.3.x-dev, 1.1.x-dev].
    - Can only install one of: vlucas/phpdotenv[2.4.x-dev, 1.1.x-dev].
    - Can only install one of: vlucas/phpdotenv[v2.2.0, 1.1.x-dev].
    - Can only install one of: vlucas/phpdotenv[v2.2.1, 1.1.x-dev].
    - Can only install one of: vlucas/phpdotenv[v2.3.0, 1.1.x-dev].
    - Can only install one of: vlucas/phpdotenv[v2.4.0, 1.1.x-dev].
    - Installation request for vlucas/phpdotenv (locked at 1.1.x-dev) -> satisfiable by vlucas/phpdotenv[1.1.x-dev].

Installation failed, reverting ./composer.json to its original content.

**Comment by unicodeveloper** [comment]
Laravel 5.1 ships with `vlucas/phpdotenv` of version 1.1.1 . And this Jusibe PHP library uses version `vlucas/phpdotenv` of version 2.2. So you either have to update the `phpdotenv` library to 2.2 or you upgrade your Laravel version.

Check this out [https://github.com/laravel/framework/blob/5.2/composer.json](https://github.com/laravel/framework/blob/5.2/composer.json)

Also, check this out [https://github.com/laravel/framework/blob/5.1/composer.json](https://github.com/laravel/framework/blob/5.1/composer.json)

**Conclusion:** Please update your Laravel version to 5.2
